### ISSUE TITLE
Request: Command triggers kawaii scene

### ISSUE THREAD

**Issue by Aliyss** [Daniele122898/SoraBot-v2#5]
Can you add some command that will trigger the bot to send a gif and text that refer to the anime scene where sora ramble stuff about what mankind seek is kawaiiness in the chest battle?
~『　 』#7114

[Link to gif.](https://imgur.com/dCFgsvy)

**Comment by Daniele122898** [comment]
added with main Command Name being "kawaii". aliases can be checked with help and are
"cute", "men", "man", "cuteness", "kawai"
