### ISSUE TITLE
STARBOARD ANNOYING AF

### ISSUE THREAD

**Issue by Daniele122898** [Daniele122898/SoraBot-v2#72]
System.NullReferenceException: Object reference not set to an instance of an object.
   at SoraBot_v2.Services.StarboardService.ClientOnReactionAdded(Cacheable`2 cacheable, ISocketMessageChannel socketMessageChannel, SocketReaction reaction) in C:\Users\danie\Documents\Coding\SoraBot-v2\SoraBot-v2\SoraBot-v2\Services\StarboardService.cs:line 144

**Comment by sn0w** [comment]
> `\Coding\SoraBot-v2\SoraBot-v2\SoraBot-v2`

![](https://cdn.discordapp.com/emojis/317006804808630293.png?v=1&size=64)

**Comment by Daniele122898** [comment]
> > `\Coding\SoraBot-v2\SoraBot-v2\SoraBot-v2`
> 
> ![](https://camo.githubusercontent.com/965cb73b38f5095da6664867d8d2867380b860a8/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3331373030363830343830383633303239332e706e673f763d312673697a653d3634)

oke so there's a reason for this. SO Sorabot-v2 is the repository name which also includes the soramusic bot. the next folder gets created when u create the project in rider and the next one i have no more excuses for.
