### ISSUE TITLE
Music Player

### ISSUE THREAD

**Issue by Aliyss** [Daniele122898/SoraBot-v2#8]
_Edit:_
User is in a voice channel and uses the commands:
-play
-yt
-sc

If Sora isn't joined to a voice channel.
Then make Sora automatically join to the voice channel the command is coming from.

**Comment by Daniele122898** [comment]
When the $play or $yt command are used.

**Comment by sn0w** [comment]
$import and $moe should probably trigger this behavior too

**Comment by ParadoxOrigins** [comment]
![image](https://user-images.githubusercontent.com/25114435/39646306-42226170-4fdb-11e8-80a5-d386e856f942.png)

Additional comment: 🥖

**Comment by catrenelle** [comment]
🐱
