### ISSUE TITLE
Unique Waifus

### ISSUE THREAD

**Issue by Serraniel** [Daniele122898/SoraBot-v2#87]
Some idea to extend the waifu service; adding unique waifus (probably via the request project). Here are some ideas on how they may work:
A user can submit an unique waifu. An unique waifu cannot be gathered through waifu boxes by other users, so you are the only user who has this waifu. You can only have one unique waifu at the same time. Submitting an unique waifu does not get you coins but you have to pay with 3-5 ultimate waifus you own (a user can select which ones he wants to burn). Animated unique waifus do cost more ultimate waifus. Changing a unique waifu will make you pay for the new waifu again. After changing, the old unique waifu will be added with random rarity to the normal waifus. Animated unique waifus will become an ultimate waifus, instead. A unique waifu can be set to the profile.

**Comment by Daniele122898** [comment]
As development on sora is... well... kinda ded i think this is smth for the backlog. If i start dev again..

This is alot of changes and DB changes and whatnot and i focus more on smaller implementations and bug fixes.
